repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest stable version
    hooks:
    -   id: black
        language_version: python3.12

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest stable version
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [pre-commit]
        verbose: true 