type: object
required:
  - source
properties:
  source:
    type: object
    required:
      - name
      - wss_url
      - type
      - subscription
    properties:
      name:
        type: string
      wss_url:
        type: string
        format: uri-reference
        pattern: "^wss?://"  # Must be ws:// or wss://
      type:
        type: string
        enum: ["coinbase"]
      subscription:
        type: object
        required:
          - product_ids
          - channels
        properties:
          product_ids:
            type: array
            minItems: 1  # Must have at least one product
            uniqueItems: true  # No duplicates
            items:
              type: string
              pattern: "^[A-Z]+-[A-Z]+$"  # e.g., BTC-USD
          channels:
            type: array
            minItems: 1  # Must have at least one channel
            uniqueItems: true  # No duplicates
            items:
              type: string
              enum:
                - "ticker"
                - "level2"
                - "matches"
                - "full"
                - "heartbeat"
additionalProperties: false  # No extra top-level properties allowed